/**
 * Plumbing. DO NOT EDIT this file.
 */
import defaultDict, { DEFAULT_LANG } from './dictionaries/default'
import translations from './dictionaries/translations'
import type { I18nKey } from './dictionaries/default'
import type { Lang } from './dictionaries/translations'

const lang = process.env.LANG?.replace(/\.UTF-8$/, '') || DEFAULT_LANG

function getTranslation(): Record<number, string> | null {
  if (lang === DEFAULT_LANG) return null

  const availableLangs = Object.keys(translations) as Lang[]

  const match =
    availableLangs.find((l) => l === lang) ??
    availableLangs.find((l) => l.startsWith(lang.split('_')[0] + '_'))

  return match ? translations[match] : null
}

const translation = getTranslation()

export function i18n(key: I18nKey): string {
  if (!translation) return key
  return translation[defaultDict[key]]
}
